service: seg3904-jobliss-api # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  environment:
    TEST_KEY: "${self:custom.tokens.TEST_KEY}"

package:
  exclude:
    - tokens.yml
    # - node_modules/puppeteer/.local-chromium/**

custom:
  stage: ${opt:stage, self:provider.stage}
  tokens: ${file(tokens.yml):${self:custom.stage}}

# you can define service wide environment variables here
#  environment:
#    variable1: value1


functions:
  scrapeIndeed:
    handler: api-handler.scrapeIndeed
    events:
      - http:
          path: indeed
          method: GET
          cors: true

  scrapeMonster:
    handler: api-handler.scrapeMonster
    events:
      - http:
          path: monster
          method: get
          cors: true

  scrapeJobBanks:
      handler: api-handler.scrapeJobBanks
      events:
        - http:
            path: jobbanks
            method: get
            cors: true          
          
  scrapeWowJobs:
    handler: api-handler.scrapeWowJobs
    events:
      - http:
          path: wowjobs
          method: get
          cors: true
